### ISSUE TITLE
Cannot run samples

### ISSUE THREAD

**Issue by loganwhite** [NetSys/S6#5]
After running ./s6ctl Got issue as follows:
```
~/S6/s6ctl$ ./s6ctl
Ubuntu 16.04.6 LTS
Ubuntu 16.04.6 LTS
Controller listening on x.x.x.x:9999
Type "help" for more information.
xun-umh-b20 (app:echo) $ start-host
Ubuntu 16.04.6 LTS
Environment variable "BESS_PKT_SIZE" is not set. Using default value "1514"
Environment variable "BESS_NUM_FLOWS" is not set. Using default value "65536"
Environment variable "BESS_QSIZE" is not set. Using default value "2048"
sudo: no tty present and no askpass program specified
sudo: no tty present and no askpass program specified
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/home/wendi/S6/s6ctl/bess_config/udpgen_multi_source.bess", line 46, in <module>
    num_out_q=NUM_QUEUES, size_inc_q=QSIZE, size_out_q=QSIZE)
  File "/home/wendi/bess/bessctl/../pybess/port.py", line 42, in __init__
    self.choose_arg(None, kwargs))
  File "/home/wendi/bess/bessctl/../pybess/bess.py", line 372, in create_port
    return self._request('CreatePort', request)
  File "/home/wendi/bess/bessctl/../pybess/bess.py", line 261, in _request
    raise self.Error(code, errmsg, query=name, query_arg=req_dict)
*** Error: Cannot attach vdev eth_vhost_v0_0,iface=/tmp/bessd/vhost_user0_0.sock,queues=1
  BESS daemon response - errno=19 (ENODEV: No such device)
       query: CreatePort
   query_arg: {'name': 'v0_0', 'num_inc_q': 1, 'size_inc_q': 2048, 'driver': 'PMDPort', 'num_out_q': 1, 'size_out_q': 2048, 'arg': {'type_url': 'type.googleapis.com/bess.pb.PMDPortArg', 'value': '";eth_vhost_v0_0,iface=/tmp/bessd/vhost_user0_0.sock,queues=1'}}
  Command failed: run file /home/wendi/S6/s6ctl/bess_config/udpgen_multi_source.bess
Cleaning up...
Ubuntu 16.04.6 LTS
Traceback (most recent call last):
  File "./s6ctl", line 102, in <module>
    sys.exit(main())
  File "./s6ctl", line 86, in main
    run_cli(args.app)
  File "./s6ctl", line 58, in run_cli
    cli.loop()
  File "/home/wendi/S6/s6ctl/cli.py", line 514, in loop
    self.process_one_line()
  File "/home/wendi/S6/s6ctl/cli.py", line 426, in process_one_line
    self.call_func(func, args)
  File "/home/wendi/S6/s6ctl/cli.py", line 397, in call_func
    func(*args)
  File "/home/wendi/S6/s6ctl/commands.py", line 208, in host_start
    cli.s6ctl.start_host_daemon()
  File "/home/wendi/S6/s6ctl/s6controller.py", line 327, in start_host_daemon
    host.start_host_daemon(self.hostenv, bessdconfig)
  File "/home/wendi/S6/s6ctl/s6controller.py", line 120, in start_host_daemon
    self.ssh_cmd(bessd_cmd)
  File "/home/wendi/S6/s6ctl/s6controller.py", line 105, in ssh_cmd
    return subprocess.check_output(shlex.split(local_cmd))
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/wendi/S6/s6ctl/host_config/id_rsa', '-p', '2799', '-o', 'StrictHostKeyChecking=no', '-o', 'BatchMode=yes', '127.0.0.1', 'export BESS_KPPS="10000"; export BESS_CONTAINERS="3";  /home/wendi/S6/script/init_host_daemon.sh ']' returned non-zero exit status 1
```

**Comment by knodir** [comment]
This error is a key here.
```
*** Error: Cannot attach vdev eth_vhost_v0_0,iface=/tmp/bessd/vhost_user0_0.sock,queues=1
  BESS daemon response - errno=19 (ENODEV: No such device)
```

Problem is on BESS side. If I remember correctly, BESS creates virtual interface(s) on the ports you connect to it. Here, it is not able to find that port. Read about the workflow here [Connecting VMs to BESS with Vhost Ports](https://github.com/NetSys/bess/wiki/Hooking-up-BESS-Ports#connecting-vms-to-bess-with-vhost-ports).

Also, you might want to install BESS separately and see if it works cleanly. Run sample examples in BESS repo to confirm you have the right setup and understand virtual interface based communication to be able to debug it.

**Comment by loganwhite** [comment]
@knodir Thank you Nodir, I'm still not quite understand the workflow here. BESS has been successfully installed. My QUESTION, for now, is: do I need to start some container or VM before running S6?
